name: Publish JavaScript Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths:
      - 'javascript/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install modules
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: cd javascript && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
